### ISSUE TITLE
Існуюче програмне забезпечення вибраної області

### ISSUE THREAD

**Issue by nadiakhantia** [nadiakhantia/DP_test#2]
http://www.echometer.com/index.html - розробка програмного забезпечення для навчання, аналізу та оптимізації продуктивності нафтових, газових і водяних свердловин у всьому світі.
http://www.gotheta.com/products.asp -каталог програм, більшість з яких - демонстраційні 
http://promtk.com/calc/pump/ - розрахунок продуктивності штангового глибинного насоса(онлайн-калькулятор) //інші калькулятори
http://www.sc-ats.ru/prodaction.html - автоматизація технологічних систем

**Comment by BrunIF** [comment]
Робіть огляд. І дивіться до #3 
Хочу вже побачити якесь оновлення.

**Comment by nadiakhantia** [comment]
як тут завантажувати файли?

**Comment by BrunIF** [comment]
які саме файли? Закидайте у репозиторій. Якщо то щось не важливе і не відноситься до диплому, тоді на файлообмінник, а тут посилання.
