### ISSUE TITLE
Зробити виправдення

### ISSUE THREAD

**Issue by BrunIF** [nadiakhantia/DP_test#4]
У остнньому комміті 5986643e4ff93a0a93f2e0f72a3425de21ce2ac7 зробіть виправлення.
Червоне - обов’язково виправити та доповнити.
Жовте - потрібно оюговорити.

Потрібно переробити повнісю зміст. 
Після правок у розділах - роздрукуйте їх.
Спочатку покажіть мені, а не Вовку.

**Comment by nadiakhantia** [comment]
я вчора вас шукала, навіть дзвонила...) зрозуміла вже свою помилку, незручна ситуація получилась)

**Comment by BrunIF** [comment]
Нічого страшного. Робіть правки. Завтра зустрінемось.
Все зрозуміло, що потрібно правити?

**Comment by nadiakhantia** [comment]
так, працюю над цим:)
